// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The Text Analytics API is a suite of natural language processing (NLP) services built with best-in-class Microsoft machine learning algorithms.  The API can be used to analyze unstructured text for tasks such as sentiment analysis, key phrase extraction and language detection. Functionality for analysis of text specific to the healthcare domain and personal information are also available in the API. Further documentation can be found in <a href="https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/overview">https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/overview</a>
public isolated client class Client {
    final http:Client clientEp;
    final readonly & ApiKeysConfig apiKeyConfig;
    # Gets invoked to initialize the `connector`.
    #
    # + apiKeyConfig - API keys for authorization 
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ApiKeysConfig apiKeyConfig, ConnectionConfig config =  {}, string serviceUrl = "https://westus.api.cognitive.microsoft.com/text/analytics/v3.1") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
        self.apiKeyConfig = apiKeyConfig.cloneReadOnly();
    }

    # Submit analysis job
    #
    # + headers - Headers to be sent with the request 
    # + payload - Collection of documents to analyze and tasks to execute 
    # + return - A successful call results with an Operation-Location header used to check the status of the analysis job 
    remote isolated function submitAnalysisJob(AnalyzeBatchInput payload, map<string|string[]> headers = {}) returns http:Response|error {
        string resourcePath = string `/analyze`;
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get analysis status and results
    #
    # + jobId - Job ID for Analyze
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Analysis job status and metadata 
    remote isolated function getAnalysisJob(string jobId, map<string|string[]> headers = {}, *GetAnalysisJobQueries queries) returns AnalyzeJobState|error {
        string resourcePath = string `/analyze/jobs/${getEncodedUri(jobId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get healthcare analysis job status and results
    #
    # + jobId - Job ID
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function getHealthcareJob(string jobId, map<string|string[]> headers = {}, *GetHealthcareJobQueries queries) returns HealthcareJobState|error {
        string resourcePath = string `/entities/health/jobs/${getEncodedUri(jobId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Cancel healthcare prediction job
    #
    # + jobId - Job ID
    # + headers - Headers to be sent with the request 
    # + return - Cancel Job request has been received 
    remote isolated function cancelHealthcareJob(string jobId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/entities/health/jobs/${getEncodedUri(jobId)}`;
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Submit healthcare analysis job
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Collection of documents to analyze 
    # + return - Accepted - call results in a link where the status of the submitted job can be checked via the GET operation 
    remote isolated function submitHealthcareJob(MultiLanguageBatchInput payload, map<string|string[]> headers = {}, *SubmitHealthcareJobQueries queries) returns http:Response|error {
        string resourcePath = string `/entities/health/jobs`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Named Entity Recognition
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Collection of documents to analyze 
    # + return - A successful call results in a list of recognized entities returned for each valid document 
    remote isolated function recognizeEntities(MultiLanguageBatchInput payload, map<string|string[]> headers = {}, *RecognizeEntitiesQueries queries) returns EntitiesResult|error {
        string resourcePath = string `/entities/recognition/general`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Entities containing personal information
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Collection of documents to analyze 
    # + return - A successful call results in a list of entities containing personal information returned for each valid document 
    remote isolated function recognizePiiEntities(MultiLanguageBatchInput payload, map<string|string[]> headers = {}, *RecognizePiiEntitiesQueries queries) returns PiiResult|error {
        string resourcePath = string `/entities/recognition/pii`;
        map<Encoding> queryParamEncoding = {"piiCategories": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Linked entities from a well known knowledge base
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Collection of documents to analyze 
    # + return - A successful call results in a list of recognized entities with links to a well known knowledge base returned for each valid document 
    remote isolated function linkEntities(MultiLanguageBatchInput payload, map<string|string[]> headers = {}, *LinkEntitiesQueries queries) returns EntityLinkingResult|error {
        string resourcePath = string `/entities/linking`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Key Phrases
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Collection of documents to analyze 
    # + return - A successful response results in 0 or more key phrases identified in each valid document 
    remote isolated function extractKeyPhrases(MultiLanguageBatchInput payload, map<string|string[]> headers = {}, *ExtractKeyPhrasesQueries queries) returns KeyPhraseResult|error {
        string resourcePath = string `/keyPhrases`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Detect Language
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Collection of documents to analyze for language endpoint 
    # + return - A successful call results in the detected language with the highest probability for each valid document 
    remote isolated function detectLanguage(LanguageBatchInput payload, map<string|string[]> headers = {}, *DetectLanguageQueries queries) returns LanguageResult|error {
        string resourcePath = string `/languages`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Sentiment
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Collection of documents to analyze 
    # + return - A successful call results in a document sentiment prediction, as well as sentiment scores for each sentiment class (Positive, Negative, and Neutral) 
    remote isolated function analyzeSentiment(MultiLanguageBatchInput payload, map<string|string[]> headers = {}, *AnalyzeSentimentQueries queries) returns SentimentResponse|error {
        string resourcePath = string `/sentiment`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Ocp-Apim-Subscription-Key"] = self.apiKeyConfig.ocpApimSubscriptionKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }
}
